title: Haoyu Wang's Personal Homepage
page-top-title: Haoyu Wang
top-section-bg-text: Logic
backgrounds:
  - static/assets/background/background_1.jpg
  - static/assets/background/banner_bg.png
  - static/assets/background/logicians_photos.jpg
  - static/assets/background/logicians1.png
  - static/assets/background/logicians2.png
  - static/assets/background/logicians3.png
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Haoyu Wang 2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/jade1997
license-link:
  text: License
  href: https://github.com/jade1997/jade1997.github.io
sections:
  - id: home
    nav: HOME
    title: Haoyu Wang&ensp;|&ensp;王昊玉
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
